apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Test Public Component
  description: A test public component for the backstage POC
  tags:
    - typescript
    - aws-lambda
    - python
  annotations:
    backstage.io/techdocs-ref: dir:./docs/
spec:
  type: service
  lifecycle: production
  owner: hannahroyal
